name:                website
version:             0.1.0.0
github:              "githubuser/website"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/website#readme>

dependencies:
- aeson == 1.5.6.0
- base >= 4.7 && < 5
- bytestring == 0.10.12.0
- clay == 0.13.3
- cmark == 0.6
- containers == 0.6.2.1
- directory == 1.3.6.0
- http-media == 0.8.0.0
- lucid == 2.9.12.1
- mtl == 2.2.2
- servant == 0.18.2
- servant-lucid == 0.9.0.2
- servant-server == 0.18.2
- tagsoup == 0.14.8
- text == 1.2.4.1
- warp == 3.3.14

default-extensions:
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- KindSignatures
- MultiParamTypeClasses
- OverloadedStrings
- StandaloneDeriving
- TypeApplications
- TypeOperators

library:
  source-dirs: src

executables:
  website:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - website

tests:
  website-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - website
    - hspec == 2.7.8
    - QuickCheck == 2.14.2
